version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.development" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.development

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.development" }}

      - run:
          name: run lint
          command: |
            python3 -m venv venv
            . venv/bin/activate
            ./tasks lint

      - run:
          name: run tests
          command: |
            python3 -m venv venv
            . venv/bin/activate
            ./tasks test

      - store_artifacts:
          path: test-reports
          destination: test-reports
